{
 "title": "Mag Copy",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } },
   {
    "name": "instance",
    "label": "Приставка",
    "query": {
     "query": "label_values(node_load1{job=\"mag250\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "All", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Список приставок",
   "type": "table",
   "gridPos": { "h": 26, "w": 18, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "node_uptime_seconds{job=\"mag250\"}"
    },
    {
     "expr": "time() - last_over_time(timestamp(changes(mag_exporter_last_update_timestamp[2m]) > 0)[24h:15s])"
    },
    {
     "expr": "mag250_device_info{job=\"mag250\"}"
    },
    {
     "expr": "last_over_time(up{job=\"mag250\"}[72h])"
    },
    {
     "expr": "rate(node_cpu_seconds_total{job=\"mag250\", mode=\"system\"}[1m])"
    },
    {
     "expr": "sum by (instance) (rate(mag250_process_cpu_ticks{job=\"mag250\", name=\"PlayerApp\"}[1m])) "
    }
   ]
  },
  {
   "title": "Player + cpu",
   "type": "state-timeline",
   "gridPos": { "h": 26, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "(\n(sum by(instance) (rate(mag250_process_cpu_ticks{job=\"mag250\", name=\"PlayerApp\"}[1m])) < 1.5) * 1\n)\nor\n(\n(rate(node_cpu_seconds_total{job=\"mag250\", mode=\"system\"}[1m]) * 100 < 5) * 2\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Online",
   "type": "state-timeline",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "last_over_time(up{job=\"mag250\"}[24h])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System",
   "type": "state-timeline",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 27 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{job=\"mag250\", mode=\"system\"}[1m]) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Player",
   "type": "state-timeline",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(mag250_process_cpu_ticks{job=\"mag250\", name=\"PlayerApp\"}[1m])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AUD[0].DecTask",
   "type": "state-timeline",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 27 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(mag250_process_cpu_ticks{job=\"mag250\", name=\"AUD[0].DecTask\"}[1m])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Audio AUD[0].PESTask",
   "type": "state-timeline",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(mag250_process_cpu_ticks{job=\"mag250\", name=\"AUD[0].PESTask\"}[1m])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Audio AUD[0].PPTask",
   "type": "state-timeline",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 40 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(mag250_process_cpu_ticks{job=\"mag250\", name=\"AUD[0].PPTask\"}[1m])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Audio AUD[0].SPDIFP",
   "type": "state-timeline",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(mag250_process_cpu_ticks{job=\"mag250\", name=\"AUD[0].SPDIFP\"}[1m])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"mag250\"}[1m]) * 8",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "{$instance}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 }, "repeat": "instance" },
  {
   "title": "Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "mag250_device_info{instance=~\"$instance\"}"
    },
    {
     "expr": "node_uptime_seconds{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(up{instance=~\"$instance\"}[240h])"
    }
   ]
  },
  {
   "title": "Нагрузка по процессам",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(mag250_process_cpu_ticks{instance=~\"$instance\"}[1m])) / 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "UDP Stream",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mag250_udp_streams_total{instance=~\"$instance\"}"
    },
    {
     "expr": "mag250_hw_decoder_active{type=\"video\", instance=~\"$instance\"}"
    },
    {
     "expr": "mag250_hw_decoder_active{type=\"audio\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Incoming Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$instance\"}[1m]) * 8"
    }
   ]
  },
  {
   "title": "Зависшие процессы (Blocked)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (name) (mag250_process_blocked{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Free RAM (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$instance\"} / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Total process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 76 },
   "targets": [
    {
     "expr": "node_procs_total{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "LA 1 min",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 79 },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$instance\"}"
    }
   ]
  }
 ]
}